import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mountApp} from '../../frontend/ui.mjs';
const {JSDOM}=createRequire('/usr/local/lib/hermes-agent/package.json')('jsdom');
const tick=()=>new Promise(r=>setTimeout(r,10));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const button=(d,n)=>[...d.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===n || b.textContent.trim()===n);
async function setup(request=()=>undefined){
 const dom=new JSDOM('<div id="app"></div>',{url:'https://fixture.test/hermes/',pretendToBeVisual:true}),win=dom.window,doc=win.document,calls=[],streams=[];
 class Events{constructor(){this.listeners={};streams.push(this);}addEventListener(n,f){this.listeners[n]=f;}emit(n,data){this.listeners[n]?.({data:JSON.stringify(data)});}close(){}}
 win.EventSource=Events;
 const app=await mountApp(doc,{clear(){},async request(p,o={}){calls.push({p,o});const v=await request(p,o);if(v!==undefined)return v;
 if(p==='/auth/me')return {user:{id:'owner',status:'ready'}};
 if(p.startsWith('/sessions?'))return {items:[{id:'s',title:'Fixture'}],total:1};
 if(p.includes('/messages'))return {items:[],run:{id:'r',session_id:'s',status:'running',input:'Original'}};
 if(p.endsWith('/controls'))return {steering:true,attempts:[]};
 if(p.endsWith('/steer'))return {status:'accepted_unconfirmed',...o.body};
 if(p.endsWith('/stop'))return {status:'stopping'};
 return {items:[]};}},win);
 button(doc,'Fixture').click();await tick();
 return {doc,win,calls,streams,app,edit(text){const t=doc.querySelector('textarea');t.value=text;t.dispatchEvent(new win.Event('input'));return t;},close(){app.destroy();win.close();}};
}
test('fresh storage offers explicit recovered retry bound to server run/key/input, not composer text',async()=>{const h=await setup(p=>p.endsWith('/controls')?{steering:true,attempts:[{id:'a',run_id:'r',input:'Guidance',idempotency_key:'server-key',status:'unknown'}]}:undefined);try{assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);h.edit('Unrelated new draft');const retry=button(h.doc,'Retry this steering request');assert.ok(retry);retry.click();await tick();const post=h.calls.find(c=>c.p.endsWith('/steer'));assert.equal(post.p,'/runs/r/steer');assert.deepEqual(post.o.body,{input:'Guidance',idempotency_key:'server-key'});assert.equal(h.doc.querySelector('textarea').value,'Unrelated new draft');button(h.doc,'Back to chats').click();await tick();retry.click();await tick();assert.equal(h.calls.filter(c=>c.p.endsWith('/steer')).length,1);}finally{h.close();}});
for(const status of ['accepted_unconfirmed','rejected','not_delivered'])test(`new typed action does not reuse ${status} key`,async()=>{const h=await setup(p=>p.endsWith('/steer')?{status}:undefined);try{h.edit('Same text');button(h.doc,'Steer current run').click();await tick();h.edit('Same text');button(h.doc,'Steer current run').click();await tick();const posts=h.calls.filter(c=>c.p.endsWith('/steer'));assert.equal(posts.length,2);assert.notEqual(posts[0].o.body.idempotency_key,posts[1].o.body.idempotency_key);}finally{h.close();}});
test('explicit record retry never consumes a separately typed same-text draft',async()=>{const h=await setup(p=>p.endsWith('/controls')?{steering:true,attempts:[{run_id:'r',input:'Guidance',idempotency_key:'server-key',status:'unknown'}]}:undefined);try{h.edit('Guidance');button(h.doc,'Retry this steering request').click();await tick();assert.equal(h.doc.querySelector('textarea').value,'Guidance');}finally{h.close();}});
for(const foreign of [{run_id:'other-run'},{run_id:'r',user_id:'other-owner'}])test(`foreign recovered attempt cannot retry ${JSON.stringify(foreign)}`,async()=>{const h=await setup(p=>p.endsWith('/controls')?{steering:true,attempts:[{...foreign,input:'Guidance',idempotency_key:'foreign-key',status:'unknown'}]}:undefined);try{assert.equal(button(h.doc,'Retry this steering request'),undefined);assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);}finally{h.close();}});
test('recovered retry is fenced by terminal run and later negative receipt',async()=>{let status='unknown';const h=await setup(p=>p.endsWith('/controls')?{steering:true,attempts:[{run_id:'r',input:'Guidance',idempotency_key:'server-key',status}]}:undefined);try{const stale=button(h.doc,'Retry this steering request');h.streams[0].emit('done',{status:'completed'});await tick();assert.equal(button(h.doc,'Retry this steering request'),undefined);stale.click();await tick();assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);status='not_delivered';h.win.dispatchEvent(new h.win.Event('focus'));await tick();stale.click();await tick();assert.equal(button(h.doc,'Retry this steering request'),undefined);assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);}finally{h.close();}});
test('unknown record retry does not turn same-text new draft into an implicit old-key retry',async()=>{const h=await setup(p=>p.endsWith('/steer')?{status:'unknown'}:p.endsWith('/controls')?{steering:true,attempts:[{run_id:'r',input:'Guidance',idempotency_key:'server-key',status:'unknown'}]}:undefined);try{h.edit('Guidance');button(h.doc,'Retry this steering request').click();await tick();button(h.doc,'Steer current run').click();await tick();const posts=h.calls.filter(c=>c.p.endsWith('/steer'));assert.equal(posts.length,2);assert.notEqual(posts[1].o.body.idempotency_key,'server-key');}finally{h.close();}});
for(const lostResponse of [false,true])test(`same-current dedicated retry preserves unchanged composer key (lostResponse=${lostResponse})`,async()=>{
 const h=await setup(p=>p.endsWith('/steer')?lostResponse?Promise.reject(new Error('lost response')):{status:'unknown'}:undefined);
 try{
  const draft=h.edit('Guidance');
  button(h.doc,'Steer current run').click();await tick();
  const original=h.calls.find(c=>c.p.endsWith('/steer'));
  assert.ok(original.o.body.idempotency_key);
  assert.equal(draft.value,'Guidance');
  assert.match(h.doc.querySelector('.steering-status').textContent,/unknown/i);
  button(h.doc,'Retry this steering request').click();await tick();
  const retries=h.calls.filter(c=>c.p.endsWith('/steer'));
  assert.equal(retries.length,2);
  assert.deepEqual(retries[1].o.body,original.o.body);
  assert.equal(draft.value,'Guidance');
  assert.match(h.doc.querySelector('.steering-status').textContent,/unknown/i);
  button(h.doc,'Steer current run').click();await tick();
  const posts=h.calls.filter(c=>c.p.endsWith('/steer'));
  assert.equal(posts.length,3);
  assert.equal(posts[2].o.body.idempotency_key,original.o.body.idempotency_key,'unedited composer retry must retain the original key after a dedicated retry');
  assert.ok(posts.every(c=>c.p==='/runs/r/steer' && c.o.body.input==='Guidance'));
  assert.equal(draft.value,'Guidance');
  assert.equal(button(h.doc,'Stop run').disabled,false);
  assert.equal(h.calls.filter(c=>c.p==='/runs').length,0);
 }finally{h.close();}
});
for(const silent of [false,true])test(`unverified persistence blocks POST (silent=${silent})`,async()=>{const h=await setup();try{h.win.Storage.prototype.setItem=function(){if(!silent)throw Error('quota denied');};h.edit('Guidance');button(h.doc,'Steer current run').click();await tick();button(h.doc,'Steer current run').click();await tick();assert.equal(h.calls.filter(c=>c.p.endsWith('/steer')).length,0);assert.equal(h.doc.querySelector('textarea').value,'Guidance');assert.match(h.doc.querySelector('.steering-status').textContent,/not sent.*stor/i);assert.equal(button(h.doc,'Stop run').disabled,false);}finally{h.close();}});
for(const terminal of [false,true])test(`newer authoritative non-delivery fences delayed accepted POST (terminal=${terminal})`,async()=>{
 const gate=deferred();let records=[];const h=await setup(p=>p.endsWith('/steer')?gate.promise:p.endsWith('/controls')?{steering:!terminal || !records.length,attempts:records,pending_steer:'Guidance',steer_receipts:records.map(a=>({run_id:'native-r',steer_id:a.idempotency_key,status:'not_delivered',accepted:false}))}:undefined);
 try{const draft=h.edit('Guidance');button(h.doc,'Steer current run').click();await tick();const body=h.calls.find(c=>c.p.endsWith('/steer')).o.body;records=[{id:'attempt-a',run_id:'r',...body,steer_id:body.idempotency_key,status:'not_delivered',created_at:1,updated_at:2}];h.streams[0].emit(terminal?'done':'steering',terminal?{status:'completed'}:{});await tick();assert.match(h.doc.querySelector('.steering-status').textContent,/Not delivered/);gate.resolve({...records[0],status:'accepted_unconfirmed',updated_at:1});await tick();assert.equal(draft.value,'Guidance');assert.match(h.doc.querySelector('.steering-status').textContent,/Not delivered/);assert.equal(h.calls.filter(c=>c.p==='/runs').length,0);}finally{h.close();}
});
for(const status of ['rejected','unknown','not_delivered'])test(`${status} preserves guidance and does not create a new turn`,async()=>{const h=await setup(p=>p.endsWith('/steer')?{status}:undefined);try{const draft=h.edit('Retain guidance');button(h.doc,'Steer current run').click();await tick();assert.equal(draft.value,'Retain guidance');assert.equal(h.calls.filter(c=>c.p==='/runs').length,0);}finally{h.close();}});
for(const fail of [false,true])test(`unsupported controls (${fail?'GET failure':'old native'}) preserves old Stop`,async()=>{const h=await setup(p=>p.endsWith('/controls')?fail?Promise.reject(new Error('offline')):{steering:false,attempts:[]}:undefined);try{assert.equal(button(h.doc,'Steer current run'),undefined);assert.ok(button(h.doc,'Stop run'));h.edit('Draft');button(h.doc,'Stop run').click();await tick();assert.equal(h.calls.filter(c=>c.p.endsWith('/stop')).length,1);assert.equal(h.doc.querySelector('textarea').value,'Draft');}finally{h.close();}});
test('late steering response cannot leave a newly started run locked or clear its draft',async()=>{
 const gate=deferred(),h=await setup((p,o)=>p.endsWith('/steer')?gate.promise:p==='/runs'?{id:'r2',session_id:'s',status:'running',input:o.body.input}:undefined);try{h.edit('Old guidance');button(h.doc,'Steer current run').click();await tick();h.streams[0].emit('done',{status:'completed'});h.edit('Explicit next turn');button(h.doc,'Send message').click();await tick();h.edit('New guidance');gate.resolve({status:'accepted_unconfirmed'});await tick();assert.equal(button(h.doc,'Steer current run').disabled,false);assert.equal(h.doc.querySelector('textarea').value,'New guidance');}finally{h.close();}
});
test('completed reentry fetches durable steering records without posting a new turn',async()=>{
 const h=await setup(p=>p.includes('/messages')?{items:[],run:null,last_run:{id:'r',session_id:'s',status:'completed'}}:p.endsWith('/controls')?{steering:false,attempts:[{input:'Saved guidance',idempotency_key:'k',status:'not_delivered'}]}:undefined);try{assert.match(h.doc.querySelector('.steering-status').textContent,/Not delivered/);assert.match(h.doc.querySelector('.steering-status').textContent,/Saved guidance/);assert.ok(button(h.doc,'Send message'));assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);}finally{h.close();}
});
test('out of order controls response cannot revoke newer capability state',async()=>{
 const gate=deferred();let n=0;const h=await setup(p=>p.endsWith('/controls')?++n===2?gate.promise:{steering:true,attempts:[]}:undefined);try{h.win.dispatchEvent(new h.win.Event('focus'));await tick();h.streams[0].emit('steering',{});await tick();gate.resolve({steering:false,attempts:[]});await tick();assert.equal(button(h.doc,'Steer current run').disabled,false);}finally{h.close();}
});
test('supported running composer separates Steer and Stop, accepts without claiming delivery',async()=>{
 const h=await setup();try{const steer=button(h.doc,'Steer current run'),stop=button(h.doc,'Stop run');assert.ok(steer,'supported run must expose steering');assert.ok(stop);assert.notEqual(steer,stop);assert.equal(stop.parentElement,h.doc.querySelector('.live-activity-heading'));assert.equal(stop.closest('details'),null);assert.equal(stop.closest('.composer'),null);assert.equal(stop.textContent.trim(),'Stop');assert.match(h.doc.querySelector('.composer').textContent,/Send another message to guide this run\./);
 const draft=h.edit('Please inspect tests');steer.click();steer.click();await tick();assert.equal(h.calls.filter(c=>c.p.endsWith('/steer')).length,1);assert.equal(h.calls.filter(c=>c.p==='/runs').length,0);assert.equal(draft.value,'');const bubble=h.doc.querySelector('.user-message[data-guidance-key]');assert.ok(bubble);assert.match(bubble.textContent,/Please inspect tests/);assert.match(bubble.textContent,/Accepted.*delivery unconfirmed/i);assert.doesNotMatch(h.doc.querySelector('.composer').textContent,/Please inspect tests/);
 }finally{h.close();}
});

test('accepted guidance is a chronological user bubble deduped across POST and SSE',async()=>{
 const gate=deferred();let records=[];const h=await setup(p=>p.endsWith('/steer')?gate.promise:p.endsWith('/controls')?{steering:true,attempts:records}:undefined);try{
 h.streams[0].emit('commentary',{text:'Before guidance'});h.edit('Change direction');button(h.doc,'Steer current run').click();await tick();assert.equal(h.doc.querySelectorAll('[data-guidance-key]').length,0);const body=h.calls.find(c=>c.p.endsWith('/steer')).o.body;
 records=[{id:'attempt-a',run_id:'r',...body,status:'accepted_unconfirmed',created_at:1,updated_at:2}];h.streams[0].emit('steering',records[0]);await tick();h.streams[0].emit('commentary',{text:'After guidance'});gate.resolve(records[0]);await tick();h.streams[0].emit('steering',records[0]);await tick();
 const bubbles=h.doc.querySelectorAll('.user-message[data-guidance-key]');assert.equal(bubbles.length,1);assert.equal(bubbles[0].dataset.guidanceKey,body.idempotency_key);assert.match(bubbles[0].textContent,/Change direction/);const transcript=h.doc.querySelector('.messages').textContent;assert.ok(transcript.indexOf('Before guidance')<transcript.indexOf('Change direction'));assert.ok(transcript.indexOf('Change direction')<transcript.indexOf('After guidance'));assert.doesNotMatch(h.doc.querySelector('.composer').textContent,/Change direction/);assert.equal(h.doc.querySelector('textarea').value,'');assert.equal(h.calls.filter(c=>c.p==='/runs').length,0);
 }finally{h.close();}
});
for(const outcome of ['accepted_unconfirmed','not_delivered','unknown'])test(`keyed guidance replay stays chronological and deduplicates controls (${outcome})`,async()=>{
 const attempt={id:'a',run_id:'r',idempotency_key:'k',input:'Replayed guidance',status:outcome,created_at:1,updated_at:2};
 const h=await setup(p=>p.includes('/messages')?{items:[],run:{id:'r',session_id:'s',status:'running',input:'Original'},tool_replay:{run_id:'r',cursor:3,events:[{id:1,name:'commentary',data:{text:'Before replay'}},{id:2,name:'steering',data:attempt},{id:3,name:'commentary',data:{text:'After replay'}}]}}:p.endsWith('/controls')?{steering:true,attempts:[attempt]}:undefined);try{const bubbles=h.doc.querySelectorAll('[data-guidance-key]');assert.equal(bubbles.length,1);assert.equal(bubbles[0].dataset.guidanceId,'a');const text=h.doc.querySelector('.messages').textContent;assert.ok(text.indexOf('Before replay')<text.indexOf('Replayed guidance'));assert.ok(text.indexOf('Replayed guidance')<text.indexOf('After replay'));assert.doesNotMatch(h.doc.querySelector('.composer').textContent,/Replayed guidance/);assert.match(bubbles[0].textContent,outcome==='not_delivered'?/Not delivered/:outcome==='unknown'?/Delivery unknown/:/Accepted.*delivery unconfirmed/);h.streams[0].emit('steering',attempt);await tick();assert.equal(h.doc.querySelectorAll('[data-guidance-key]').length,1);assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);}finally{h.close();}
});
test('terminal history guidance uses stable identities across reopen and same-text distinct attempts',async()=>{
 const attempts=['a','b'].map((id,i)=>({id,run_id:i?'r':'prior',idempotency_key:id,input:'Identical guidance',status:'accepted_unconfirmed'}));
 const items=[{role:'user',content:'Original'},...attempts.map(a=>({id:`journal:${a.run_id}:steering:${a.id}`,role:'user',kind:'guidance',content:a.input,run_id:a.run_id,steering_id:a.id,idempotency_key:a.idempotency_key,steering_status:a.status,turn_boundary:false})),{role:'assistant',content:'Final answer'}];
 const h=await setup(p=>p.includes('/messages')?{items,run:null,last_run:{id:'r',session_id:'s',status:'completed'}}:p.endsWith('/controls')?{steering:false,attempts:[attempts[1]]}:undefined);try{for(let n=0;n<2;n++){const bubbles=h.doc.querySelectorAll('.user-message[data-guidance-key]');assert.equal(bubbles.length,2);assert.equal(bubbles[1].dataset.guidanceId,'b');assert.match(bubbles[1].textContent,/Accepted.*delivery unconfirmed/);assert.doesNotMatch(h.doc.querySelector('.composer').textContent,/Identical guidance/);const text=h.doc.querySelector('.messages').textContent;assert.ok(text.lastIndexOf('Identical guidance')<text.indexOf('Final answer'));button(h.doc,'Back to chats').click();await tick();button(h.doc,'Fixture').click();await tick();}assert.equal(h.calls.filter(c=>c.o.method==='POST').length,0);}finally{h.close();}
});
for(const change of ['navigation','account'])test(`stale accepted receipt cannot add a bubble after ${change}`,async()=>{
 const gate=deferred();let owner='owner';const h=await setup(p=>p.endsWith('/steer')?gate.promise:p==='/auth/me'?{user:{id:owner,status:'ready'}}:undefined);try{h.edit('Old private guidance');button(h.doc,'Steer current run').click();await tick();if(change==='account'){owner='other';await h.app.start();}else{button(h.doc,'Back to chats').click();await tick();}gate.resolve({status:'accepted_unconfirmed'});await tick();assert.equal(h.doc.querySelectorAll('[data-guidance-key]').length,0);assert.doesNotMatch(h.doc.querySelector('#app').textContent,/Old private guidance/);}finally{h.close();}
});
test('an admitted run allows next-turn model settings without retargeting steering',async()=>{
 const h=await setup(p=>p.endsWith('/model-options')?{available:true,models:[{id:'future',provider:'fixture',label:'Future model',reasoning_efforts:[]}]}:undefined);try{const model=h.doc.querySelector('select[aria-label=Model]');assert.ok(model);assert.equal(model.disabled,false);model.selectedIndex=1;model.dispatchEvent(new h.win.Event('change'));assert.equal(h.doc.querySelector('[role=dialog]'),null);assert.deepEqual(JSON.parse(h.win.sessionStorage.getItem('hermes:owner:model-controls:'+JSON.stringify(['owner','s']))),{model:'future',provider:'fixture'});h.edit('Guidance only');button(h.doc,'Steer current run').click();await tick();const body=h.calls.find(c=>c.p.endsWith('/steer')).o.body;assert.deepEqual(Object.keys(body).sort(),['idempotency_key','input']);assert.equal(model.disabled,false);}finally{h.close();}
});
test('guidance help is plain, contextual, and never promises consumption',async()=>{
 const gate=deferred(),h=await setup(p=>p.endsWith('/steer')?gate.promise:undefined);try{const help=h.doc.querySelector('.steering-help');assert.equal(help.hidden,false);assert.equal(help.textContent,'Send another message to guide this run.');h.edit('Guidance');button(h.doc,'Steer current run').click();await tick();assert.equal(help.textContent,'Sending guidance…');assert.equal(button(h.doc,'Stop run').disabled,false);h.streams[0].emit('approval',{id:'a'});assert.equal(help.hidden,true);gate.resolve({status:'accepted_unconfirmed'});await tick();assert.equal(help.hidden,true);button(h.doc,'Stop run').click();await tick();assert.equal(help.hidden,true);assert.doesNotMatch(h.doc.querySelector('.composer').textContent,/checkpoint|current tools continue/);}finally{h.close();}
});
test('approval SSE immediately disables steering but preserves separate Stop and draft',async()=>{
 const h=await setup();try{const draft=h.edit('Retain');h.streams[0].emit('approval',{id:'a'});assert.equal(button(h.doc,'Steer current run').disabled,true);button(h.doc,'Steer current run').click();assert.equal(button(h.doc,'Stop run').disabled,false);assert.equal(draft.value,'Retain');assert.equal(h.calls.filter(c=>c.p.endsWith('/steer')).length,0);}finally{h.close();}
});
test('pending steering cannot clear same text retyped as a new draft after completion',async()=>{
 const gate=deferred(),h=await setup(p=>p.endsWith('/steer')?gate.promise:undefined);try{const draft=h.edit('Guidance');button(h.doc,'Steer current run').click();await tick();h.streams[0].emit('done',{status:'completed'});h.edit('Different');h.edit('Guidance');gate.resolve({status:'accepted_unconfirmed'});await tick();assert.equal(draft.value,'Guidance');assert.ok(button(h.doc,'Send message'));assert.equal(h.calls.filter(c=>c.p==='/runs').length,0);}finally{h.close();}
});
test('unknown explicit retry reuses durable key, Stop stays usable, navigation ignores late response',async()=>{
 let count=0;const gate=deferred(),h=await setup(p=>p.endsWith('/steer')?(++count===1?Promise.reject(new Error('lost response')):gate.promise):undefined);try{const draft=h.edit('Guidance');button(h.doc,'Steer current run').click();await tick();assert.equal(draft.value,'Guidance');assert.match(h.doc.querySelector('.steering-status').textContent,/unknown/i);h.win.dispatchEvent(new h.win.Event('focus'));await tick();assert.equal(count,1);button(h.doc,'Steer current run').click();await tick();const posts=h.calls.filter(c=>c.p.endsWith('/steer'));assert.equal(posts[0].o.body.idempotency_key,posts[1].o.body.idempotency_key);button(h.doc,'Stop run').click();await tick();assert.equal(button(h.doc,'Steer current run').disabled,true);button(h.doc,'Back to chats').click();await tick();gate.resolve({status:'accepted_unconfirmed'});await tick();button(h.doc,'Fixture').click();await tick();assert.equal(h.doc.querySelector('textarea').value,'Guidance');}finally{h.close();}
});
test('SSE not-delivered status restores cleared submitted text without auto posting',async()=>{
 let records=[];const h=await setup(p=>p.endsWith('/controls')?{steering:true,attempts:records}:undefined);try{h.edit('Keep me');button(h.doc,'Steer current run').click();await tick();records=[{...h.calls.find(c=>c.p.endsWith('/steer')).o.body,status:'not_delivered'}];h.streams[0].emit('steering',{});await tick();assert.equal(h.doc.querySelector('textarea').value,'Keep me');assert.match(h.doc.querySelector('.guidance-status').textContent,/Not delivered/);assert.equal(h.doc.querySelectorAll('[data-guidance-key]').length,1);assert.doesNotMatch(h.doc.querySelector('.composer').textContent,/Keep me/);assert.equal(h.calls.filter(c=>c.o.method==='POST').length,1);}finally{h.close();}
});
