import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mountApp} from '../../frontend/ui.mjs';
const {JSDOM}=createRequire('/usr/local/lib/hermes-agent/package.json')('jsdom');
const tick=()=>new Promise(r=>setTimeout(r,10));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};};
function click(doc,label){const el=[...doc.querySelectorAll('button')].find(e=>e.getAttribute('aria-label')===label || e.textContent===label);assert.ok(el,label);el.click();}
async function setup(override=()=>undefined){
 const dom=new JSDOM('<div id="app"></div>',{url:'https://example.com/hermes/',pretendToBeVisual:true}),win=dom.window,doc=win.document,calls=[],streams=[];
 class Events{constructor(){this.listeners={};streams.push(this);}addEventListener(n,f){this.listeners[n]=f;}emit(n,d){this.listeners[n]?.({data:JSON.stringify(d)});}close(){this.closed=true;}}
 win.EventSource=Events;
 const app=await mountApp(doc,{clear(){},async request(path,options={}){calls.push({path,options});const value=await override(path,options);if(value!==undefined)return value;if(path==='/auth/me')return {user:{id:'u',status:'ready'}};if(path.startsWith('/sessions?'))return {items:[{id:'s1',title:'First',run_status:'running'},{id:'s2',title:'Native',run_status:'unknown'}],total:2};if(path.includes('/messages'))return {items:[],run:null};return {items:[]};}},win);
 return {doc,win,app,calls,streams,async open(label='First'){click(doc,label);await tick();},close(){app.destroy();win.close();}};
}
test('session rows expose durable status and native unknown without changing names',async()=>{const h=await setup();try{const rows=h.doc.querySelectorAll('.session-row');assert.equal(rows[0].querySelector('.session-run-status')?.dataset.state,'running');assert.equal(rows[0].querySelector('.session-run-status')?.getAttribute('aria-label'),'Running');assert.equal(rows[1].querySelector('.session-run-status')?.getAttribute('aria-label'),'Status unavailable');await h.open('Native');assert.equal(h.doc.querySelector('.conversation-status').dataset.state,'unknown');}finally{h.close();}});
test('approval reconciliation scopes actions, survives errors, and rejects stale replay after Inbox decisions',async()=>{
 let pending=[{id:'a',run_id:'r1',request_id:'qa'},{id:'b',run_id:'r1',request_id:'qb'}],late;
 const h=await setup((p,o)=>{if(p==='/sessions/s1')return {id:'s1',title:'First'};if(p.includes('/messages'))return {items:[],run:{id:'r1',session_id:'s1',status:'waiting_for_approval',input:'Hi'}};if(p==='/approvals'){if(late && !late.used){late.used=true;return late.promise;}return {items:pending};}if(p==='/runs/r1')return {id:'r1',session_id:'s1',status:'waiting_for_approval'};if(p.endsWith('/decision')){pending=pending.filter(a=>!p.includes('/'+a.id+'/'));return {};}if(p==='/inbox')return {items:[{id:'i',session_id:'s1',title:'First',body:'Finished'}]};});
 try{await h.open();assert.match(h.doc.querySelector('.approval-notice')?.textContent || '',/2 actions/);const old=h.streams[0];click(h.doc,'Inbox');await tick();click(h.doc,'Deny');await tick();click(h.doc,'Open conversation');await tick();assert.match(h.doc.querySelector('.approval-notice').textContent,/1 action/);old.emit('approval',{id:'a',run_id:'r1',request_id:'qa'});assert.match(h.doc.querySelector('.approval-notice').textContent,/1 action/);late=deferred();h.win.dispatchEvent(new h.win.Event('focus'));await tick();click(h.doc,'Inbox');await tick();late.resolve({items:[{id:'a',run_id:'r1',request_id:'qa'}]});late=null;await tick();click(h.doc,'Deny');await tick();click(h.doc,'Open conversation');await tick();assert.equal(h.doc.querySelector('.approval-notice').hidden,true);h.streams.at(-1).emit('approval',{id:'a',run_id:'r1',request_id:'qa'});assert.equal(h.doc.querySelector('.approval-notice').hidden,true);}finally{h.close();}
});
test('historical running replay cannot tombstone an authoritative pending action',async()=>{const approval={id:'a',run_id:'r1'};const h=await setup(p=>p.includes('/messages')?{items:[],run:{id:'r1',session_id:'s1',status:'waiting_for_approval'}}:p==='/approvals'?{items:[approval]}:undefined);try{await h.open();assert.equal(h.doc.querySelector('.approval-notice').hidden,false);h.streams[0].emit('status',{status:'running'});h.streams[0].emit('approval',approval);await tick();assert.equal(h.doc.querySelector('.approval-notice').hidden,false);assert.equal(h.doc.querySelector('.conversation-status').dataset.state,'waiting_for_approval');}finally{h.close();}});
test('new running status clears replayed approval without clearing unrelated errors',async()=>{const h=await setup(p=>p.includes('/messages')?{items:[],run:{id:'r1',session_id:'s1',status:'running'}}:undefined);try{await h.open();const events=h.streams[0];events.emit('approval',{id:'old',run_id:'r1'});assert.equal(h.doc.querySelector('.approval-notice').hidden,false);events.listeners.delta({data:'bad json'});events.emit('status',{status:'running'});await tick();assert.equal(h.doc.querySelector('.approval-notice').hidden,true);assert.match(h.doc.querySelector('.notice').textContent,/could not be read/);events.emit('approval',{id:'old',run_id:'r1'});assert.equal(h.doc.querySelector('.approval-notice').hidden,true);}finally{h.close();}});
test('freshly submitted run approvals survive focus and account switch removes expanded draft',async()=>{let user='u';const h=await setup((p,o)=>p==='/auth/me'?{user:{id:user,status:'ready'}}:p==='/runs'?{id:'new',session_id:'s1',status:'queued'}:p==='/approvals'?{items:[{id:'pending-new',run_id:'new'}]}:p==='/runs/new'?{id:'new',session_id:'s1',status:'waiting_for_approval'}:undefined);try{await h.open();h.doc.querySelector('textarea').value='Send';click(h.doc,'Send message');await tick();h.streams[0].emit('approval',{id:'pending-new',run_id:'new'});h.win.dispatchEvent(new h.win.Event('focus'));await tick();assert.equal(h.doc.querySelector('.approval-notice').hidden,false);click(h.doc,'Expand editor');h.doc.querySelector('textarea').value='Private';h.doc.querySelector('textarea').dispatchEvent(new h.win.Event('input'));user='other';await h.app.start();assert.equal(h.doc.querySelector('[data-editor-dialog]'),null);await h.open();assert.equal(h.doc.querySelector('textarea').value,'');assert.equal(h.doc.querySelector('.approval-notice').hidden,true);}finally{h.close();}});
test('last-request context is never mislabeled current and known capacity survives unknown usage',async()=>{for(const context of [{used_tokens:42,limit_tokens:1000,source:'last_request'},{used_tokens:null,limit_tokens:1000,source:null}]){const h=await setup(p=>p.endsWith('/telemetry')?{context,model:'saved',metadata:{source:'native_session',freshness:'persisted',observed_at:null}}:undefined);try{await h.open();assert.match(h.doc.querySelector('.technical-strip').textContent,/Last persisted/);const summary=h.doc.querySelector('.technical-summary').textContent;assert.match(summary,/1000/);if(context.used_tokens!==null){assert.match(summary,/Last request context/);assert.doesNotMatch(summary,/Current context/);}}finally{h.close();}}});
test('telemetry distinguishes context from lifetime totals without unknown placeholders',async()=>{
 const h=await setup(p=>p.endsWith('/telemetry')?{model:'test-model',provider:'test-provider',context:{used_tokens:100,limit_tokens:1000,source:'native',observed_at:1720000000,estimated:false},usage:{scope:'session_lifetime',input_tokens:98765}}:undefined);try{await h.open();const strip=h.doc.querySelector('.technical-strip');assert.ok(strip);assert.match(strip.textContent,/test-model/);assert.match(strip.textContent,/100 \/ 1000.*10%/);assert.match(strip.textContent,/native/);assert.match(strip.textContent,/Session lifetime/);assert.doesNotMatch(strip.textContent,/unknown|Not available|output:/i);assert.equal(strip.nextElementSibling.className,'composer');}finally{h.close();}
 const u=await setup(p=>p.endsWith('/telemetry')?{usage:{scope:'session_lifetime',input_tokens:999999}}:undefined);try{await u.open();const strip=u.doc.querySelector('.technical-strip');assert.match(strip.textContent,/Session lifetime input: 999999/);assert.doesNotMatch(strip.textContent,/context|unknown|Not available/i);assert.doesNotMatch(u.doc.querySelector('.technical-summary').textContent,/999999/);}finally{u.close();}
});
for(const [name,data] of [
 ['model alone',{model:'saved-model',provider:null,context:{used_tokens:null,limit_tokens:null,source:null},metadata:{source:null,observed_at:null}}],
 ['provider alone',{provider:'saved-provider'}],
 ['all null',{model:null,provider:null,context:null,metadata:null,usage:null}],
 ['empty',{}],['failed request',new Error('Telemetry unavailable')]
])test(`telemetry omits unknown fields in summary and expanded details: ${name}`,async()=>{
 const h=await setup(p=>{if(p.endsWith('/telemetry')){if(data instanceof Error)throw data;return data;}});
 try{await h.open();const strip=h.doc.querySelector('.technical-strip');
  if(name==='model alone'||name==='provider alone'){assert.ok(strip && !strip.hidden);strip.open=true;assert.equal(strip.querySelector('summary').textContent,name==='model alone'?'saved-model':'saved-provider');assert.equal(strip.querySelectorAll('p').length,0);assert.doesNotMatch(strip.textContent,/unknown|Not available|Context|Source:|Observed:/i);}
  else assert.ok(!strip || strip.hidden,'no visible empty telemetry strip or disclosure');
 }finally{h.close();}
});
for(const context of [{used_tokens:0,source:'live'},{used_tokens:42,estimated:true},{limit_tokens:1000},{used_tokens:17,limit_tokens:0}])test(`partial context stays truthful: ${JSON.stringify(context)}`,async()=>{
 const h=await setup(p=>p.endsWith('/telemetry')?{context}:undefined);try{await h.open();const strip=h.doc.querySelector('.technical-strip');assert.ok(strip && !strip.hidden);assert.doesNotMatch(strip.textContent,/unknown|Not available|%|\//i);if(context.used_tokens!=null)assert.match(strip.textContent,new RegExp(String(context.used_tokens)));else assert.match(strip.textContent,/Context capacity 1000/);if(context.estimated)assert.match(strip.textContent,/Estimated context/);if(context.source==='live')assert.match(strip.textContent,/Current context/);}finally{h.close();}
});
test('saved assistant tool arguments reach bounded detail instead of a bare name',async()=>{
 const h=await setup(p=>p.includes('/messages')?{items:[{role:'assistant',content:null,tool_calls:[{id:'saved',function:{name:'terminal',arguments:JSON.stringify({command:'pytest tests/test_auth.py -q'})}}]}],run:null}:undefined);
 try{await h.open();assert.equal(h.doc.querySelector('.tool-summary')?.textContent,'pytest tests/test_auth.py -q');assert.equal(h.doc.querySelector('.tool-activity').open,false);}finally{h.close();}
});
test('Expand belongs beside the textarea at its top-right and restores the same editor slot',async()=>{
 const h=await setup();try{await h.open();const text=h.doc.querySelector('textarea'),expand=h.doc.querySelector('[aria-label="Expand editor"]');assert.equal(expand.parentElement,text.parentElement);assert.equal(expand.closest('.composer-bottom'),null);assert.equal(text.nextElementSibling,expand);const slot=text.parentElement;text.value='Preserved';text.setSelectionRange(2,4);expand.click();click(h.doc,'Done');assert.equal(text.parentElement,slot);assert.equal(text.nextElementSibling,expand);assert.equal(text.value,'Preserved');assert.equal(text.selectionStart,2);assert.equal(text.selectionEnd,4);expand.click();h.doc.querySelector('[data-editor-dialog]').dispatchEvent(new h.win.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(text.parentElement,slot);assert.equal(text.nextElementSibling,expand);}finally{h.close();}
});
test('expanded editor is the same bounded draft, traps focus and collapses without sending',async()=>{
 const h=await setup();try{await h.open();const text=h.doc.querySelector('[name=message]');text.value='Long\nmessage';text.dispatchEvent(new h.win.Event('input'));text.setSelectionRange(3,7);click(h.doc,'Expand editor');const dialog=h.doc.querySelector('[data-editor-dialog][role=dialog]');assert.ok(dialog);assert.equal(dialog.getAttribute('aria-modal'),'true');assert.equal(dialog.querySelector('textarea'),text);assert.equal(text.maxLength,32000);assert.equal(text.selectionStart,3);text.dispatchEvent(new h.win.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(h.calls.filter(c=>c.path==='/runs').length,0);text.focus();text.dispatchEvent(new h.win.KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));assert.equal(h.doc.activeElement.getAttribute('aria-label'),'Done');text.focus();text.setSelectionRange(5,5);dialog.dispatchEvent(new h.win.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(h.doc.querySelector('[data-editor-dialog]'),null);assert.equal(h.doc.querySelector('.composer textarea'),text);assert.equal(text.value,'Long\nmessage');assert.equal(text.selectionStart,5);assert.equal(h.doc.activeElement,text);click(h.doc,'Expand editor');click(h.doc,'Done');assert.equal(h.calls.filter(c=>c.path==='/runs').length,0);click(h.doc,'Expand editor');click(h.doc,'Chats');await tick();assert.equal(h.doc.querySelector('[data-editor-dialog]'),null);await h.open();assert.equal(h.doc.querySelector('textarea').value,'Long\nmessage');}finally{h.close();}
});
